# Publish docs on main branch

name: build and publish docs

# Controls when the action will run.
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    name: Create Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: [3.11]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: test 
        run: |
          echo "${GITHUB_ACTOR}"
          echo "${GITHUB_REPOSITORY}"
          echo "${GITHUB_SHA}"
          echo "${GITHUB_DOMAIN}"

      - uses: actions/checkout@v4

      - name: checkout branch 
        run: |
            git fetch origin gh-pages --depth=1

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: build documentation
        run: |
          poetry install --with dev --no-root
          poetry run mike deploy --push --update-aliases dev

    #   - name: deploy
    #     uses: peaceiris/actions-gh-pages@v3
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: ./site
